### ISSUE TITLE
ValidationError when signing up with Github

### ISSUE THREAD

**Issue by icebob** [msgbyte/tailchat#102]
Hi, 

great project. I've tried to sign up with Github social login, but it gives ValidationError:

```json
{"name":"ValidationError","message":"Parameters validation error!","code":422,"type":"VALIDATION_ERROR","data":[{"type":"required","message":"The 'email' field is required.","field":"email","actual":null,"nodeID":"14c1c2fa1840-28","action":"user.findUserByEmail"}]}
```

**Comment by moonrailgun** [comment]
Oh, my bad. Because of this plugin is register account with email... but you not has public email setting in your github account...

I will fix it.

**Comment by moonrailgun** [comment]
Yeah, I known this problem, you can retry some times. Because the server of tailchat deployed in china, sometimes the network is not very stable between tailchat and github, and needs some luck. (The chinese government does not allow users to use github and google) 

:(

-----

But tailchat is build for global, so i add it. And everything is provider by plugins

**Comment by moonrailgun** [comment]
This timeout problem has been optimize with proxy, feel free to reopen it if still occur timeout error
